### ISSUE TITLE
Previous working 'Create VM' API request throws 400 Bad Request.

### ISSUE THREAD

**Issue by PrasannaBhattarai** [cudoventures/cudo-compute-python-client#1]
My previous response body which worked shows 400 Bad request error. Is there an issue, despite VMs being available in the selected region. Any feedback? [[ASAP]]
![image](https://github.com/CudoVentures/cudo-compute-python-client/assets/100421420/98ef9865-f9e0-4bbf-adef-dfb257779a8a)

**Comment by strawbs1** [comment]
If your code was working before, it means all those machines have been used up. Sometimes slight changes in what you are requesting will allow you to get something, otherwise you may need to use a different GPU or data centre.
